

CREATE TABLE jobs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company TEXT NOT NULL,
    experience INTEGER,
    country TEXT NOT NULL,
    position TEXT NOT NULL,
    wage INTEGER
)
